services:
  api:
    build: .
    container_name: iot_api
    ports:
      - "5001:5001"
    env_file:
      - .env
    depends_on:
      - db

  db:
    image: mysql:8.0
    container_name: iot_mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
